<?php
/**
 * Created by PhpStorm.
 * User: pixco
 * Date: 19/02/2017
 * Time: 12:05 PM
 */

namespace App\Transformers;


use App\CardPower;
use League\Fractal\Scope;
use League\Fractal\TransformerAbstract;

class CardPowerTransformer extends TransformerAbstract
{

    /**
     * @param CardPower $entity
     * @return array
     */
    public function transform(CardPower $entity)
    {
        return [
            'name' => $entity->name,
            'description' => $entity->description
        ];
    }

    public function processIncludedResources(Scope $scope, $data)
    {
        return parent::processIncludedResources($scope, $data); // TODO: Change the autogenerated stub
    }
}